import type { Prisma } from "@/generated/prisma/client";

/**
 * Deliberately NOT `Db | PrismaClient` (the extended client's type vs the
 * base `rawDb` type) — calling a generic Prisma delegate method through a
 * union of those two differently-parameterized client types triggers a
 * "Excessive stack depth" compiler crash (same root cause as the
 * employee-service.ts select-type issue). This minimal structural type is
 * satisfied by `db`, a `db.$transaction` `tx`, and `rawDb` alike, so any of
 * the three can be passed without the compiler needing to reconcile their
 * full generic shapes.
 */
type AuditLogWriter = {
  auditLog: {
    create(args: { data: Prisma.AuditLogUncheckedCreateInput }): Promise<unknown>;
  };
};

export const AuditAction = {
  AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  AUTH_LOGIN_FAILED: "AUTH_LOGIN_FAILED",
  AUTH_LOGOUT: "AUTH_LOGOUT",
  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  USER_ROLE_CHANGED: "USER_ROLE_CHANGED",
  USER_ACTIVATED: "USER_ACTIVATED",
  USER_DEACTIVATED: "USER_DEACTIVATED",
  USER_INITIAL_PASSWORD_GENERATED: "USER_INITIAL_PASSWORD_GENERATED",
  USER_PASSWORD_RESET_BY_ADMIN: "USER_PASSWORD_RESET_BY_ADMIN",
  USER_PASSWORD_CHANGED: "USER_PASSWORD_CHANGED",
  USER_SESSIONS_REVOKED: "USER_SESSIONS_REVOKED",
  USER_PASSWORD_RESET_REQUESTED: "USER_PASSWORD_RESET_REQUESTED",
  USER_PASSWORD_RESET_COMPLETED: "USER_PASSWORD_RESET_COMPLETED",

  DEPARTMENT_CREATED: "DEPARTMENT_CREATED",
  DEPARTMENT_UPDATED: "DEPARTMENT_UPDATED",
  MASTER_DATA_CREATED: "MASTER_DATA_CREATED",
  MASTER_DATA_UPDATED: "MASTER_DATA_UPDATED",

  EMPLOYEE_CREATED: "EMPLOYEE_CREATED",
  EMPLOYEE_UPDATED: "EMPLOYEE_UPDATED",
  EMPLOYEE_PERSONAL_INFO_CHANGED: "EMPLOYEE_PERSONAL_INFO_CHANGED",
  EMPLOYEE_BANK_INFO_CHANGED: "EMPLOYEE_BANK_INFO_CHANGED",
  EMPLOYEE_SENSITIVE_FIELD_VIEWED: "EMPLOYEE_SENSITIVE_FIELD_VIEWED",
  EMPLOYEE_REPORTING_MANAGER_CHANGED: "EMPLOYEE_REPORTING_MANAGER_CHANGED",
  EMPLOYEE_STATUS_CHANGED: "EMPLOYEE_STATUS_CHANGED",
  EMPLOYEE_OFFBOARDED: "EMPLOYEE_OFFBOARDED",
  EMPLOYEE_USER_LINKED: "EMPLOYEE_USER_LINKED",
  EMPLOYEE_DIRECTORY_EXPORTED: "EMPLOYEE_DIRECTORY_EXPORTED",

  ASSIGNMENT_CREATED: "ASSIGNMENT_CREATED",
  ASSIGNMENT_UPDATED: "ASSIGNMENT_UPDATED",
  ASSIGNMENT_ENDED: "ASSIGNMENT_ENDED",
  AVAILABILITY_OVERRIDE_SET: "AVAILABILITY_OVERRIDE_SET",

  DOCUMENT_UPLOADED: "DOCUMENT_UPLOADED",
  DOCUMENT_DOWNLOADED: "DOCUMENT_DOWNLOADED",
  DOCUMENT_UPDATED: "DOCUMENT_UPDATED",
  DOCUMENT_ARCHIVED: "DOCUMENT_ARCHIVED",
  WORK_PASS_CREATED: "WORK_PASS_CREATED",
  WORK_PASS_UPDATED: "WORK_PASS_UPDATED",
  CERTIFICATION_CREATED: "CERTIFICATION_CREATED",
  CERTIFICATION_UPDATED: "CERTIFICATION_UPDATED",

  ATTENDANCE_CHECKED_IN: "ATTENDANCE_CHECKED_IN",
  ATTENDANCE_CHECKED_OUT: "ATTENDANCE_CHECKED_OUT",
  ATTENDANCE_RECORD_CORRECTED: "ATTENDANCE_RECORD_CORRECTED",
  HOLIDAY_CREATED: "HOLIDAY_CREATED",
  HOLIDAY_DELETED: "HOLIDAY_DELETED",

  APPROVAL_REQUEST_CREATED: "APPROVAL_REQUEST_CREATED",
  APPROVAL_REQUEST_APPROVED: "APPROVAL_REQUEST_APPROVED",
  APPROVAL_REQUEST_REJECTED: "APPROVAL_REQUEST_REJECTED",
  APPROVAL_REQUEST_CANCELLED: "APPROVAL_REQUEST_CANCELLED",
  APPROVAL_STEP_DECIDED: "APPROVAL_STEP_DECIDED",

  LEAVE_REQUEST_CREATED: "LEAVE_REQUEST_CREATED",
  LEAVE_REQUEST_CANCELLED: "LEAVE_REQUEST_CANCELLED",
  LEAVE_BALANCE_ADJUSTED: "LEAVE_BALANCE_ADJUSTED",

  PROJECT_ACTIVATED: "PROJECT_ACTIVATED",
  PROJECT_CLOSED: "PROJECT_CLOSED",
  SITE_STAGE_ADVANCED: "SITE_STAGE_ADVANCED",
  RESOURCE_REQUEST_CREATED: "RESOURCE_REQUEST_CREATED",
  RESOURCE_REQUEST_CANCELLED: "RESOURCE_REQUEST_CANCELLED",
  TASK_CREATED: "TASK_CREATED",
  TASK_STATUS_CHANGED: "TASK_STATUS_CHANGED",
  STOCK_TRANSACTION_RECORDED: "STOCK_TRANSACTION_RECORDED",

  SALARY_STRUCTURE_SET: "SALARY_STRUCTURE_SET",
  PAYROLL_PERIOD_CREATED: "PAYROLL_PERIOD_CREATED",
  PAYROLL_RUN_PROCESSED: "PAYROLL_RUN_PROCESSED",
  PAYSLIP_DISBURSED: "PAYSLIP_DISBURSED",
  PAYSLIP_VIEWED: "PAYSLIP_VIEWED",
  PAYROLL_STATUTORY_EXPORTED: "PAYROLL_STATUTORY_EXPORTED",

  WAREHOUSE_CREATED: "WAREHOUSE_CREATED",
  WAREHOUSE_UPDATED: "WAREHOUSE_UPDATED",
  PURCHASE_ORDER_CREATED: "PURCHASE_ORDER_CREATED",
  PURCHASE_ORDER_SUBMITTED: "PURCHASE_ORDER_SUBMITTED",
  GOODS_RECEIPT_POSTED: "GOODS_RECEIPT_POSTED",
  STOCK_TRANSFER_CREATED: "STOCK_TRANSFER_CREATED",
  STOCK_TRANSFER_DISPATCHED: "STOCK_TRANSFER_DISPATCHED",
  STOCK_TRANSFER_RECEIVED: "STOCK_TRANSFER_RECEIVED",

  LEAD_CREATED: "LEAD_CREATED",
  LEAD_STATUS_CHANGED: "LEAD_STATUS_CHANGED",
  LEAD_CONVERTED_TO_PROJECT: "LEAD_CONVERTED_TO_PROJECT",
  TENDER_UPDATED: "TENDER_UPDATED",
  TENDER_SUBMITTED: "TENDER_SUBMITTED",
  QUOTATION_CREATED: "QUOTATION_CREATED",
  QUOTATION_STATUS_CHANGED: "QUOTATION_STATUS_CHANGED",

  PROJECT_DOCUMENT_UPLOADED: "PROJECT_DOCUMENT_UPLOADED",
  PROJECT_DOCUMENT_ARCHIVED: "PROJECT_DOCUMENT_ARCHIVED",
  BUDGET_LINE_SET: "BUDGET_LINE_SET",
  PROGRESS_CLAIM_SUBMITTED: "PROGRESS_CLAIM_SUBMITTED",
  DEFECT_ITEM_LOGGED: "DEFECT_ITEM_LOGGED",
  DEFECT_ITEM_STATUS_CHANGED: "DEFECT_ITEM_STATUS_CHANGED",
} as const;

export type AuditAction = (typeof AuditAction)[keyof typeof AuditAction];

export type RecordAuditLogInput = {
  userId?: string | null;
  action: AuditAction;
  entityType: string;
  entityId?: string | null;
  beforeData?: Prisma.InputJsonValue | null;
  afterData?: Prisma.InputJsonValue | null;
  metadata?: Prisma.InputJsonValue | null;
  ipAddress?: string | null;
  userAgent?: string | null;
  requestId?: string | null;
};

/**
 * Writes an audit-log row. Never pass passwords, password hashes, session
 * tokens, or other secrets in `beforeData`/`afterData`/`metadata`.
 *
 * Accepts `db`, a `tx`, or `rawDb` (see `AuditLogWriter` above) — the last
 * one for the handful of pre-tenant-context bootstrap call sites (e.g. an
 * unresolvable-company login failure).
 */
export async function recordAuditLog(
  client: AuditLogWriter,
  input: RecordAuditLogInput
) {
  await client.auditLog.create({
    data: {
      userId: input.userId ?? null,
      action: input.action,
      entityType: input.entityType,
      entityId: input.entityId ?? null,
      beforeData: input.beforeData ?? undefined,
      afterData: input.afterData ?? undefined,
      metadata: input.metadata ?? undefined,
      ipAddress: input.ipAddress ?? null,
      userAgent: input.userAgent ?? null,
      requestId: input.requestId ?? null,
    },
  });
}
